export const data = [
    {
        id: 2,
        title: "Dune",
        body: "Paul Atreides, çöllerin gezegeni Arrakis'i kontrol etmek için ailesiyle birlikte gönderilir. Ancak, bu gezegendeki güç mücadelesinde kendini keşfeder ve Arrakis'in kaderini değiştirecek liderliğe yükselir.",
        rate: 8.3,
        tags: ["Action", "Adventure", "Drama", "Sci-Fi"],
        date: 2021,
    },
    {
        id: 3,
        title: "Tenet",
        body: "An agent, who can manipulate time, takes on a dangerous mission to save the world from a destructive war, fighting against a mysterious terrorist group.",
        rate: 7.8,
        tags: ["Action", "Sci-Fi", "Thriller"],
        date: 2020,
    },
    {
        id: 4,
        title: "Joker",
        body: "Arthur Fleck is an outcast, and gradually descends into madness, becoming the psychopathic character known as Joker in the crime-filled world of Gotham City.",
        rate: 8.4,
        tags: ["Crime", "Drama", "Thriller"],
        date: 2019,
    },
    {
        id: 5,
        title: "Avengers: Endgame",
        body: "After the devastating actions of Thanos with his Infinity Gauntlet, the surviving superheroes come together to undo the destruction and restore balance to the universe.",
        rate: 8.4,
        tags: ["Action", "Adventure", "Drama", "Sci-Fi"],
        date: 2018,
    },
    {
        id: 6,
        title: "The Shape of Water",
        body: "A mute cleaning woman forms a unique bond with an amphibious creature that is being held in captivity in a secret government laboratory, leading to an unexpected romance.",
        rate: 7.3,
        tags: [
            "Adventure",
            "Drama",
            "Fantasy",
            "Romance",
            "Sci-Fi",
            "Thriller",
        ],
        date: 2017,
    },
    {
        id: 7,
        title: "La La Land",
        body: "An aspiring actress and a jazz musician in Los Angeles pursue their dreams of success, but their careers threaten to pull them apart.",
        rate: 8.0,
        tags: ["Comedy", "Drama", "Music", "Romance"],
        date: 2016,
    },
    {
        id: 8,
        title: "Mad Max: Fury Road",
        body: "Max is forced to join a desert community ruled by a ruthless leader. However, a woman named Furiosa escapes, and convinces Max to help them in their quest for freedom, leading to an epic journey.",
        rate: 8.1,
        tags: ["Action", "Adventure", "Sci-Fi", "Thriller"],
        date: 2015,
    },
    {
        id: 9,
        title: "Interstellar",
        body: "A group of astronauts must travel through a wormhole in space to find habitable planets, in order to provide a new home for humanity's future.",
        rate: 8.6,
        tags: ["Adventure", "Drama", "Sci-Fi"],
        date: 2014,
    },
    {
        id: 10,
        title: "Gravity",
        body: "After a space accident leaves her stranded alone, an astronaut must rely on her wits and resilience to survive.",
        rate: 7.7,
        tags: ["Drama", "Sci-Fi", "Thriller"],
        date: 2013,
    },
    {
        id: 11,
        title: "The Avengers",
        body: "Superheroes unite to fight against Loki and his army, protecting the Earth in an epic battle.",
        rate: 8.0,
        tags: ["Action", "Adventure", "Sci-Fi"],
        date: 2012,
    },
    {
        id: 13,
        title: "Harry Potter and the Deathly Hallows - Part 2",
        body: "The final chapter of the Harry Potter series where Harry, Ron, and Hermione continue their quest to destroy the Horcruxes and defeat Lord Voldemort.",
        rate: 8.1,
        tags: ["Adventure", "Drama", "Fantasy", "Mystery"],
        date: 2011,
    },
    {
        id: 12,
        title: "Inception",
        body: "Thieves perform corporate espionage by infiltrating the subconscious of their targets, but Dom Cobb is tasked with a dangerous mission to regain his freedom.",
        rate: 8.8,
        tags: ["Action", "Adventure", "Sci-Fi", "Thriller"],
        date: 2010,
    },
];
